stages:
  - build_and_test
  - containerize
  - deploy

build_and_test:
  stage: build_and_test
  image: node:latest
  tags:
    - lutdevops2023
  script:
    - npm install
    - npm run test

containerize:
  stage: containerize
  image: docker:latest
  services:
    - docker:dind
  tags:
    - lutdevops2023
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

deploy:
  stage: deploy
  tags:
    - lutdevops2023
  script:
    - echo "Deploy to Azure App Service"
  environment:
    # define the environment name
    # define the environment URL